# fly.toml app configuration file generated for luna-app-backend-dev on 2023-12-25T13:10:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "gru"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
restarts = { policy = 'on-fail' }

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
