// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-us'

export type Locales =
	| 'de'
	| 'en-us'
	| 'es'
	| 'fr'
	| 'pt-br'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!
	 * @param {unknown} name
	 */
	hi_name: RequiredParams<'name'>
	/**
	 * I​f​ ​y​o​u​ ​d​i​d​ ​n​o​t​ ​c​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​,​ ​p​l​e​a​s​e​ ​i​g​n​o​r​e​ ​t​h​i​s​ ​e​m​a​i​l​.
	 */
	if_you_did_not_request_this_email_ignore_it: string
	/**
	 * I​f​ ​y​o​u​ ​h​a​v​e​ ​a​n​y​ ​q​u​e​s​t​i​o​n​s​,
	 */
	if_you_have_any_questions: string
	/**
	 * c​o​n​t​a​c​t​ ​u​s​.
	 */
	contact_us: string
	/**
	 * T​h​i​s​ ​i​s​ ​y​o​u​r​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​,​ ​i​n​s​e​r​t​ ​i​t​ ​i​n​ ​t​h​e​ ​a​p​p​.
	 */
	this_is_your_verification_code: string
	/**
	 * H​i​ ​{​n​a​m​e​}​,​ ​h​e​r​e​ ​i​s​ ​y​o​u​r​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​.
	 * @param {string} name
	 */
	hi_name_here_is_your_verification_code: RequiredParams<'name'>
	/**
	 * D​o​ ​n​o​t​ ​s​h​a​r​e​ ​t​h​i​s​ ​c​o​d​e​ ​w​i​t​h​ ​a​n​y​o​n​e​.
	 */
	do_not_share_this_code_with_anyone: string
	/**
	 * L​u​n​a​ ​L​o​g​o
	 */
	logo_alt_text: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}!
	 */
	hi_name: (arg: { name: unknown }) => LocalizedString
	/**
	 * If you did not create an account, please ignore this email.
	 */
	if_you_did_not_request_this_email_ignore_it: () => LocalizedString
	/**
	 * If you have any questions,
	 */
	if_you_have_any_questions: () => LocalizedString
	/**
	 * contact us.
	 */
	contact_us: () => LocalizedString
	/**
	 * This is your verification code, insert it in the app.
	 */
	this_is_your_verification_code: () => LocalizedString
	/**
	 * Hi {name}, here is your verification code.
	 */
	hi_name_here_is_your_verification_code: (arg: { name: string }) => LocalizedString
	/**
	 * Do not share this code with anyone.
	 */
	do_not_share_this_code_with_anyone: () => LocalizedString
	/**
	 * Luna Logo
	 */
	logo_alt_text: () => LocalizedString
}

export type Formatters = {}
