site_name: LunaCrew | Accounts-core
site_description: Accounts Core API - Luna's User Management
site_author: LunaCrew
site_url: https://lunacrew.github.io/accounts-core

repo_name: GitHub
repo_url: https://github.com/LunaCrew/accounts-core

docs_dir: pages
site_dir: site

nav:
  - Home: index.md
  - API: api.md
  - Architecture: architecture.md
  - Contribute: contribute.md
  - Stacks: stacks.md
  - References: references.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      type: material/alert-circle
  logo: assets/luna.png
  favicon: assets/luna.png

  palette:
    # Default color palette
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: brown
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: brown
      accent: indigo

  features:
    - navigation.footer
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LunaCrew

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid