#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

MESSAGE=$(cat $1) 
COMMITFORMAT="^(feat|fix|docs|style|ref|test|setup)(\((.*)\))?:\s?(.*)$"

if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
echo -e '\033[1;34m# Commit message\033[0m\n'
  echo -e "\033[1;31m⛔ Your commit was rejected due to the commit message. COMMIT FAILED!\033[0m\n" 
  echo -e "\033[4;37mPlease use the following format:\033[0m"
  echo ""
  echo -e "- \033[0;32mfeat: feature example comment\033[0m"
  echo -e "- \033[0;32mfix: fix example comment\033[0m"
  echo -e "- \033[0;32mbug: bugfix example comment\033[0m"
  echo -e "- \033[0;32mdocs: docs example comment\033[0m"
  echo -e "- \033[0;32mstyle: style example comment\033[0m"
  echo -e "- \033[0;32mref: ref example comment\033[0m"
  echo -e "- \033[0;32mtest: test example comment\033[0m"
  echo " "
  exit 1
fi